### PR TITLE
Add allen favorite color - green

### PR DESCRIPTION
**Pull request by githubteacher**
This Pull Request adds a line for favorite color to Allen's profile.

### CODE REVIEW

**Comment by githubteacher** [comment]
This looks good to me! :+1:

**Comment by brntbeer** [comment]
What if we edited the top part of the email and called out that it was email?

**Comment by brntbeer** [comment]
Would that change appear IN this pull request?

**Comment by githubteacher** [comment]
It sure will!

**Comment by githubteacher** [comment]
Let's ship this!  :shipit:

**Comment by brntbeer** [comment]
:+1:

**Pull request merged**
